through_the_lens_app/config/routes.rb
Rails.application.routes.draw do
  get '/home' => "pages#home"

  get '/about' => "pages#about"

  root 'sessions#new'
  resources :users
  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'

  resources :shares, only: [:index, :new, :create, :update, :edit, :show, :destroy]

end

through_the_lens_app/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :share
end

through_the_lens_app/app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :title, :link
end

through_the_lens_app/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :shares
  has_many :comments

  validates :email, presence: true, uniqueness: true
end

through_the_lens_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    helper_method :current_user

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

through_the_lens_app/app/controllers/concerns/shares_controller.rb
class SharesController < ApplicationController

  def index
    @shares = Share.where(category: params[:category])
  end
end

through_the_lens_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

through_the_lens_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

through_the_lens_app/app/controllers/shares_controller.rb
class SharesController < ApplicationController

  def show
    @share = Share.find(params[:id])
  end

  def index
    @shares = Share.where(category: params[:category])
  end

  def new
    @share = Share.new
    @share.category = params[:category]
  end

  def edit
    @share = Share.find(params[:id])
  end

  def update
    @share = Share.find(params[:id])
    @share.category = params[:category]
    @share.update(share_params)
    redirect_to '/shares?category=' + @share.category
  end

  def create
    @share = Share.new(share_params)
    @share.user = current_user
    if @share.save
      redirect_to '/shares?category=' + @share.category
    else
      flash.now.alert = "Both Title and Link are Required"
      render :new
    end
  end

  def destroy
    @share = Share.find(params[:id])
    @share.destroy
    redirect_to '/shares?category=' + @share.category
  end

  private
  def share_params
    params.require(:share).permit(:link, :title, :description, :category, :artist, :length, :address, :album)
  end
end

through_the_lens_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have successfully signed up!"
      session[:user_id] = @user.id
      redirect_to home_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to home_path
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :img, :location)
  end
end

through_the_lens_app/app/helpers/application_helper.rb
module ApplicationHelper
end

through_the_lens_app/app/helpers/pages_helper.rb
module PagesHelper
end

through_the_lens_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

through_the_lens_app/app/helpers/users_helper.rb
module UsersHelper
end

through_the_lens_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThroughTheLens</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
</head>
<body>


<nav class="navbar navbar-inverse">
  <div class="container">
      <div class="col-lg-6 col-xs-12">
        <%= link_to home_path, class: "navbar-brand" do %>
          Home
        <% end %>
        <%= link_to about_path, class: "navbar-brand" do %>
          About
        <% end %>
      </div>

      <div class="col-lg-6 col-xs-12 text-right" >
        <% if current_user %>
          <%= link_to "Art", shares_path(category: "Art"), class: "btn btn-default navbar-btn", class: "btn btn-danger", type: "button" %>
          <%= link_to "Music", shares_path(category: "Music"), class: "btn btn-default navbar-btn", class: "btn btn-success" %>
          <%= link_to "Coffeeshops", shares_path(category: "Coffeeshops"), class: "btn btn-default navbar-btn", class: "btn btn-info" %>
          <%= link_to "Tech", shares_path(category: "Tech"), class: "btn btn-default navbar-btn", class: "btn btn-warning" %>
          <%= link_to('Your Profile', user_path(current_user), class: "btn btn-default navbar-btn", class: "btn btn-secondary", type: "button") if params[:controller] != "users" %>
          <%= link_to 'Log Out', session_path(' '), class: "btn btn-default navbar-btn", class: "btn btn-secondary", type: "button", method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_session_path, class: "btn btn-default navbar-btn", class: "btn btn-success", type: "button" %>

          <%= link_to "Join the Gang", new_user_path, class: "btn btn-default navbar-btn", class: "btn btn-warning", type: "button" %>
        <% end %>
      </div>
  </div>
</nav>

<%= yield %>

</body>

</html>

through_the_lens_app/app/views/pages/about.html.erb
<div class="col-sm-6 col-sm-offset-1">
  <h1>About</h1>
    <p>This is a little getaway where users can add links to art,
    music videos, coffee shops and technologies they'd like to share with the rest
    of the community.</p>
<img id="aboutpage" src="http://img15.deviantart.net/fcdb/i/2015/040/1/1/life_through_the_lens_by_kabdul-d8hf6xr.jpg">
</div>

through_the_lens_app/app/views/pages/home.html.erb
<div class="container">
  <h1>What would you like to do?</h1>
</div>

<div class="col-sm-6 col-sm-offset-1">
  <h2>Check out some ...</h2>
    <div class="text-xs-center">
<img class="img-rounded" src="https://i.imgur.com/BPMIuzW.jpg" width="1024" height="684">
    </div>
</div>

through_the_lens_app/app/views/shares/edit.html.erb
<div class="container">
  <h1>Edit Content</h1>

  <p><%= alert %></p>

<div class="col-sm-6 col-sm-offset-1">
  <%= form_for @share do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :artist %>
      <%= f.text_field :artist, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.collection_select :category, Share.select('distinct category'), :category, :category, {class: "form-control"}  %>
    </div>
    <!-- <%= f.hidden_field :category, value: @share.category %> -->
    <%= f.submit "Edit Share", {class: "btn btn-success"} %>
  <% end %>
</div>
</div>

through_the_lens_app/app/views/shares/index.html.erb
<div class="container">
  <div class="row" >
    <div class="col-xs-6">
      <h1><%= params[:category] %></h1>
    </div>
    <div class="col-xs-6 text-right">
      <%= link_to "CREATE", new_share_path + "?category=" + params[:category] %>
    </div>
</div>

<% @shares.each do |share| %>
<div class="row row-spacing">
  <div class="col-xs-6">
    <% if share.link.include? "youtube" %>
        <iframe class="" src="<%= share.link %>"></iframe>
      <% else %>
        <img class="img-responsive" src="<%= share.link %>" alt="a pretty thing belongs here">
      <% end %>
  </div>
  <div class="col-xs-6">
    <h3><%= share.title %></h3>
    <h2><%= share.artist %></h3>
    <h2><%= share.description %></h2>
    <h2><%= share.length %></h2>
    <h2><%= share.album %></h2>
    <h2><%= share.address %></h2>
    <% if share.user == current_user %>
  <h4><%= link_to "delete", share_path(share), method: :delete %> |
      <%= link_to "edit", edit_share_path(share) + "?category=" + params[:category], method: :get %></h4>
    <% end %>
    <% if share.user.img %>
      <img src="<%= share.user.img %>" width="75px">
    <% end %>
    <h4><%= share.user.username %> <small>(<%= share.user.location %>)</small></h4>
  </div>
</div>
<% end %>
</div>

through_the_lens_app/app/views/shares/new.html.erb
<div class="container">
  <h1>New Share</h1>

  <p><%= alert %></p>

<div class="col-sm-6 col-sm-offset-1">
  <%= form_for @share do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :artist %>
      <%= f.text_field :artist, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, {class: "form-control"}  %>
    </div>
    <div class="form-group">
      <%= f.label :category %>
      <%= f.collection_select :category, Share.select('distinct category'), :category, :category, {class: "form-control"}  %>
    </div>
    <!-- <%= f.hidden_field :category, value: @share.category %> -->
    <%= f.submit "Create Share", {class: "btn btn-success"} %>
  <% end %>
</div>
</div>

through_the_lens_app/app/views/users/new.html.erb
<div class="col-sm-6 col-sm-offset-1">
  <div class="jumbotron">
    <h1>To Join the Gang, Simply Fill out your ...</h1>
    <%= bootstrap_form_for @user do |f| %>
      <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.password_field :password %>
    </div>
  <div class="field">
    <%= f.password_field :password_confirmation %>
  </div>
    <div class="field">
      <%= f.text_field :location %>
    </div>
    <div class="field">
        <%= f.text_field :img, label: "Image URL" %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>
  </div>
</div>

through_the_lens_app/app/views/users/show.html.erb
<div class="col-sm-6 col-sm-offset-1">
<h4>What your profile looks like</h4>
  <%= bootstrap_form_for @user do |f| %>
      <%= f.text_field :email %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
      <br>
      <%= f.text_field :location %>
      <%= f.text_field :img, label: "Image URL" %>
      <%= f.submit "Submit" %>
  <% end %>
</div>